/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#4edea3',
        'on-surface-variant': '#434655',
        'on-error': '#ffffff',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#003ea8',
        'on-tertiary-container': '#bdffdb',
        'surface-variant': '#e0e3e5',
        'surface-bright': '#f7f9fb',
        'primary-container': '#2563eb',
        'surface-container-highest': '#e0e3e5',
        'inverse-surface': '#2d3133',
        'on-secondary-container': '#5c647a',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#bec6e0',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eceef0',
        'on-secondary-fixed': '#131b2e',
        'surface-tint': '#0053db',
        outline: '#737686',
        secondary: '#565e74',
        'on-surface': '#191c1e',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed': '#00174b',
        'secondary-container': '#dae2fd',
        'on-tertiary-fixed': '#002113',
        'on-background': '#191c1e',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-container': '#007d55',
        'on-primary-container': '#eeefff',
        'outline-variant': '#c3c6d7',
        tertiary: '#006242',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-dim': '#d8dadc',
        'surface-container-low': '#f2f4f6',
        'tertiary-fixed': '#6ffbbe',
        surface: '#f7f9fb',
        error: '#ba1a1a',
        'surface-container-high': '#e6e8ea',
        'secondary-fixed': '#dae2fd',
        'inverse-primary': '#b4c5ff',
        'inverse-on-surface': '#eff1f3',
        background: '#f7f9fb',
        primary: '#004ac6',
        'primary-fixed-dim': '#b4c5ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        'margin-desktop': '48px',
        sm: '8px',
        lg: '24px',
        xs: '4px',
        xl: '32px',
        base: '4px',
        'margin-mobile': '16px',
        gutter: '16px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'title-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        display: ['Inter'],
        'tabular-nums': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'tabular-nums': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
      boxShadow: {
        level2: '0px 4px 12px rgba(15, 23, 42, 0.05)',
        level3: '0px 12px 32px rgba(15, 23, 42, 0.1)',
      },
    },
  },
  plugins: [],
}
